{
 "title": "Chia",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Chia Farmed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_chia_farmed", "legendFormat": "Total Farmed" }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "SUM(plot_count)", "legendFormat": "Total Plots" },
    { "expr": "SUM (delta(plot_count[24h]))", "legendFormat": "{{job}} Last 24" },
    { "expr": "SUM(plot_count) * 101 / 1024 ", "legendFormat": "Plotted Space (TiB)" }
   ]
  },
  {
   "title": "Plotter Tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(SUM BY(job) (COUNT BY(job, pid) (plotter_state)))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Plots/hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "COUNT by(job) (delta(completed_plots[24h])) / 24",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "COUNT (delta(completed_plots[24h])) / 24",
     "legendFormat": "total"
    },
    { "expr": "SUM(plot_count)", "legendFormat": "Plot Count" }
   ]
  },
  {
   "title": "Phase Timings",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AVG by(job, phase) (phase_timings{job=\"hppro\"} / 60 / 60)",
     "legendFormat": "{{job}}::{{phase}}"
    },
    {
     "expr": "SUM(AVG by(job, phase) (phase_timings{job=\"hppro\"} / 60 / 60))",
     "legendFormat": "hppro:total"
    },
    {
     "expr": "AVG by(job, phase) (phase_timings{job=\"capi\"} / 60 / 60)",
     "legendFormat": "{{job}}::{{phase}}"
    },
    {
     "expr": "SUM(AVG by(job, phase) (phase_timings{job=\"capi\"} / 60 / 60))",
     "legendFormat": "capi::total"
    }
   ]
  },
  {
   "title": "Plot Locations",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plot_count > 0", "legendFormat": "{{job}}::{{path}}" }
   ]
  },
  {
   "title": "Netspace vs Win Chance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "pbytes" }
   ],
   "targets": [
    { "expr": "netspace_estimate_pib", "legendFormat": "Netspace" },
    {
     "expr": "1 / (1 - ((1 - (SUM(plot_count)* 0.0982254 * 0.000976562) / SUM(netspace_estimate_pib))^4608))",
     "legendFormat": "Days to Win"
    }
   ]
  },
  {
   "title": "Plotter Progress",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort_desc(plotter_state )", "legendFormat": "{{job}}_{{tag}}_{{pid}}" }
   ]
  },
  {
   "title": "Disk Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(drive_writes[1m])", "legendFormat": "{{job}}::{{device}}" }
   ]
  },
  {
   "title": "Ram vs Swap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "chia_host_max_ram - chia_host_used_ram",
     "legendFormat": "{{job}}"
    },
    { "expr": "chia_host_swap_usage", "legendFormat": "{{job}}_swap" }
   ]
  },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "drive_free_mb", "legendFormat": "{{job}}::{{path}}" }
   ]
  }
 ]
}